<a href="https://colab.research.google.com/github/MOHAN-DATTA-24/NLP/blob/main/Word_Embedding_using__Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## Speech Of DR APJ Abdul Kalam
paragraph = """I have three visions for India. In 3000 years of our history, people from all over
               the world have come and invaded us, captured our lands, conquered our minds.
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours.
               Yet we have not done this to any other nation. We have not conquered anyone.
               We have not grabbed their land, their culture,
               their history and tried to enforce our way of life on them.
               Why? Because we respect the freedom of others.That is why my
               first vision is that of freedom. I believe that India got its first vision of
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India
               stands up to the world, no one will respect us. Only strength respects strength. We must be
               strong not only as a military power but also as an economic power. Both must go hand-in-hand.
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life.
               I see four milestones in my career"""

In [2]:
import nltk

In [7]:
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [9]:
nltk.download('punkt')
sentences = nltk.sent_tokenize(paragraph)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [6]:
lemma = WordNetLemmatizer()

In [5]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [11]:
corpus_lemma = []

In [12]:
for i in range(len(sentences)):
  review = re.sub('[^a-zA-Z]',' ',sentences[i])
  review = review.lower()
  review = review.split()
  review_lemmatize = [lemma.lemmatize(word,pos='v') for word in review if not word in set(stopwords.words('english'))]
  review_lemmatize = ' '.join(review_lemmatize)
  corpus_lemma.append(review_lemmatize)

In [19]:
corpus_lemma

['three visions india',
 'years history people world come invade us capture land conquer mind',
 'alexander onwards greeks turks moguls portuguese british french dutch come loot us take',
 'yet do nation',
 'conquer anyone',
 'grab land culture history try enforce way life',
 '',
 'respect freedom others first vision freedom',
 'believe india get first vision start war independence',
 'freedom must protect nurture build',
 'free one respect us',
 'second vision india development',
 'fifty years develop nation',
 'time see develop nation',
 'among top nations world term gdp',
 'percent growth rate areas',
 'poverty level fall',
 'achievements globally recognise today',
 'yet lack self confidence see develop nation self reliant self assure',
 'incorrect',
 'third vision',
 'india must stand world',
 'believe unless india stand world one respect us',
 'strength respect strength',
 'must strong military power also economic power',
 'must go hand hand',
 'good fortune work three great mind'

#**One Hot Representation**

In [20]:
onehot_repr=[one_hot(words,voc_size)for words in corpus_lemma]
print(onehot_repr)

[[386, 47, 26], [297, 470, 201, 76, 256, 342, 30, 132, 225, 389, 215], [294, 148, 320, 342, 463, 230, 241, 204, 84, 256, 127, 30, 123], [292, 335, 434], [389, 413], [191, 225, 356, 470, 263, 481, 390, 226], [], [427, 488, 156, 85, 470, 488], [59, 26, 26, 85, 470, 42, 115, 241], [488, 29, 307, 153, 415], [16, 471, 427, 30], [174, 470, 26, 168], [459, 297, 388, 434], [387, 51, 388, 434], [303, 270, 485, 76, 202, 361], [110, 150, 228, 238], [303, 63, 215], [168, 430, 29, 170], [292, 77, 268, 311, 51, 388, 434, 268, 499, 268, 478], [288], [219, 470], [26, 29, 287, 76], [59, 461, 26, 287, 76, 471, 427, 30], [24, 427, 24], [29, 235, 498, 348, 495, 284, 348], [29, 12, 462, 462], [292, 325, 154, 386, 226, 215], [384, 321, 431, 382], [345, 270, 496, 423, 285, 384, 301, 13, 388, 348, 382], [320, 154, 386, 190, 241, 226, 387, 226], [51, 457, 378, 223]]


In [14]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [15]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [16]:
### Vocabulary size
voc_size=500

In [17]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [18]:
import numpy as np

In [21]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0   0 386  47  26]
 [ 76 256 342  30 132 225 389 215]
 [230 241 204  84 256 127  30 123]
 [  0   0   0   0   0 292 335 434]
 [  0   0   0   0   0   0 389 413]
 [191 225 356 470 263 481 390 226]
 [  0   0   0   0   0   0   0   0]
 [  0   0 427 488 156  85 470 488]
 [ 59  26  26  85 470  42 115 241]
 [  0   0   0 488  29 307 153 415]
 [  0   0   0   0  16 471 427  30]
 [  0   0   0   0 174 470  26 168]
 [  0   0   0   0 459 297 388 434]
 [  0   0   0   0 387  51 388 434]
 [  0   0 303 270 485  76 202 361]
 [  0   0   0   0 110 150 228 238]
 [  0   0   0   0   0 303  63 215]
 [  0   0   0   0 168 430  29 170]
 [311  51 388 434 268 499 268 478]
 [  0   0   0   0   0   0   0 288]
 [  0   0   0   0   0   0 219 470]
 [  0   0   0   0  26  29 287  76]
 [ 59 461  26 287  76 471 427  30]
 [  0   0   0   0   0  24 427  24]
 [  0  29 235 498 348 495 284 348]
 [  0   0   0   0  29  12 462 462]
 [  0   0 292 325 154 386 226 215]
 [  0   0   0   0 384 321 431 382]
 [423 285 384 301  1

In [22]:
## 10 feature dimesnions
dim=10

In [23]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [28]:
print(corpus_lemma[0])
print(onehot_repr[0])
print(embedded_docs[0])

three visions india
[386, 47, 26]
[  0   0   0   0   0 386  47  26]


In [29]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 118ms/step


array([[-0.02506287,  0.01559495,  0.01230221,  0.0040404 , -0.03065288,
         0.01828947, -0.01824779,  0.02374562,  0.04537145,  0.01647589],
       [-0.02506287,  0.01559495,  0.01230221,  0.0040404 , -0.03065288,
         0.01828947, -0.01824779,  0.02374562,  0.04537145,  0.01647589],
       [-0.02506287,  0.01559495,  0.01230221,  0.0040404 , -0.03065288,
         0.01828947, -0.01824779,  0.02374562,  0.04537145,  0.01647589],
       [-0.02506287,  0.01559495,  0.01230221,  0.0040404 , -0.03065288,
         0.01828947, -0.01824779,  0.02374562,  0.04537145,  0.01647589],
       [-0.02506287,  0.01559495,  0.01230221,  0.0040404 , -0.03065288,
         0.01828947, -0.01824779,  0.02374562,  0.04537145,  0.01647589],
       [-0.00406208, -0.04490309,  0.00236202,  0.04337244,  0.00624459,
         0.0120214 , -0.01526573,  0.02898469,  0.01391866,  0.04891619],
       [-0.00772749,  0.01644112,  0.01730089,  0.04786675, -0.01814518,
        -0.03845812, -0.02716149, -0.03824797

In [30]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 195ms/step
[[[-2.50628721e-02  1.55949481e-02  1.23022087e-02 ...  2.37456225e-02
    4.53714468e-02  1.64758898e-02]
  [-2.50628721e-02  1.55949481e-02  1.23022087e-02 ...  2.37456225e-02
    4.53714468e-02  1.64758898e-02]
  [-2.50628721e-02  1.55949481e-02  1.23022087e-02 ...  2.37456225e-02
    4.53714468e-02  1.64758898e-02]
  ...
  [-4.06207889e-03 -4.49030884e-02  2.36202404e-03 ...  2.89846919e-02
    1.39186643e-02  4.89161871e-02]
  [-7.72749260e-03  1.64411180e-02  1.73008926e-02 ... -3.82479653e-02
    1.43461935e-02  3.11281942e-02]
  [-2.51508113e-02  4.10776772e-02 -3.37900892e-02 ...  1.12573989e-02
    4.62888964e-02  2.58065350e-02]]

 [[ 4.81809117e-02  1.31557323e-02  2.58723237e-02 ... -6.90191984e-03
    3.17432918e-02 -3.17594409e-02]
  [-2.18059905e-02 -7.22867250e-03 -2.38557812e-02 ...  3.44035774e-03
    1.43226646e-02  1.15309246e-02]
  [-2.12749727e-02  1.19225495e-02  3.04677822e-02 ... -1.23263001e-02
    2.474166

#**Bag Of Words**

In [31]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
model_BOW= cv.fit_transform(corpus_lemma).toarray()

In [32]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(model_BOW,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [33]:
model1=Sequential()
model1.add(Embedding(voc_size,10,input_length=sent_length))
model1.compile('adam','mse')

In [34]:
model1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [35]:
print(corpus_lemma[0])
print(onehot_repr[0])
print(embedded_docs[0])

three visions india
[386, 47, 26]
[0 1 0 0 0 0 0 0]


In [36]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 20ms/step


array([[-0.02506287,  0.01559495,  0.01230221,  0.0040404 , -0.03065288,
         0.01828947, -0.01824779,  0.02374562,  0.04537145,  0.01647589],
       [ 0.04331633,  0.03876591,  0.02796575,  0.00899247,  0.00435245,
        -0.00083194, -0.03847482, -0.00552166,  0.02798232, -0.04287965],
       [-0.02506287,  0.01559495,  0.01230221,  0.0040404 , -0.03065288,
         0.01828947, -0.01824779,  0.02374562,  0.04537145,  0.01647589],
       [-0.02506287,  0.01559495,  0.01230221,  0.0040404 , -0.03065288,
         0.01828947, -0.01824779,  0.02374562,  0.04537145,  0.01647589],
       [-0.02506287,  0.01559495,  0.01230221,  0.0040404 , -0.03065288,
         0.01828947, -0.01824779,  0.02374562,  0.04537145,  0.01647589],
       [-0.02506287,  0.01559495,  0.01230221,  0.0040404 , -0.03065288,
         0.01828947, -0.01824779,  0.02374562,  0.04537145,  0.01647589],
       [-0.02506287,  0.01559495,  0.01230221,  0.0040404 , -0.03065288,
         0.01828947, -0.01824779,  0.02374562